version: '3.8'
name: myapp
services:
  app:
    image: abeerseada/go-app-with-db
    container_name: go-container
    environment:
      MONGO_URI: mongodb://db:27017
      SERVER_PORT: 8080

    depends_on: 
    - db
    ports:
    - "8080:8080"

  db:
    image: mongo:latest
    ports:
    - 27017:27017
    container_name: mongo-container
    volumes:
    - mongo-data:/data/db
volumes:
  mongo-data:
